[package]
authors = ["AriPerkkio <ari.perkkio@gmail.com>"]
edition = "2021"
name = "rollup-plugin-local-import"
version = "0.0.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
swc = "0.221.1"
swc_common = { version = "0.27.13", features = ["tty-emitter"] }
swc_ecma_ast = "0.90.15"
swc_ecma_parser = "0.118.2"
swc_ecma_visit = "0.76.6"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
