/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformResult {
  code: string
  map: string
}
export function localImport(callback: (path: string) => string): Plugin
export class Plugin {
  /** Public plugin properties https://rollupjs.org/guide/en/#properties */
  name: string
  /** Build hook: https://rollupjs.org/guide/en/#transform */
  transform(sourceCode: string, filename: string): TransformResult
  /** Build hook: https://rollupjs.org/guide/en/#buildend */
  buildEnd(): void
}
