/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TransformResult {
  code: string
}
export function localImport(callback: (path: string) => string): Plugin
export class Plugin {
  name: string
  transform(sourceCode: string): TransformResult
  buildEnd(): void
}
